"""Our first initial database, we have simply added users.

Revision ID: 69a3f32dd441
Revises: None
Create Date: 2016-01-19 16:41:14.432195

"""

# revision identifiers, used by Alembic.
revision = '69a3f32dd441'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
