"""Added equipment table to the database.

Revision ID: 6decd80da190
Revises: 69a3f32dd441
Create Date: 2016-01-23 15:03:36.991513

"""

# revision identifiers, used by Alembic.
revision = '6decd80da190'
down_revision = '69a3f32dd441'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=2400), nullable=True),
    sa.Column('description', sa.String(length=2400), nullable=True),
    sa.Column('requires_human', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    ### end Alembic commands ###
